[package]
name = "obstgarten"
version = "0.1.0"
authors = ["Diego Fioravanti <fioravanti.diego@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.17.3"
rand = "0.8"
